# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Build Catnip LibOS

concurrency:
  group: azure-catnip
  cancel-in-progress: true

on:
  push:
    branches:
      - bugfix-*
      - enhancement-*
      - feature-*
      - workaround-*
      - dev
      - unstable
      - master

env:
  CARGO_TERM_COLOR: always
  GITHUB_REPOSITORY: $GITHUB_REPOSITORY
  GITHUB_SHA: $GITHUB_SHA

jobs:

  #====================
  # Setup
  #====================

  # Demikernel 0
  setup-demikernel0:
    name: Setup
    uses: demikernel/workflows/.github/workflows/setup.yml@dev
    secrets:
      host: ${{ secrets.CATNIP_HOSTNAME_A }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  # Demikernel 1
  setup-demikernel1:
    name: Setup
    uses: demikernel/workflows/.github/workflows/setup.yml@dev
    secrets:
      host: ${{ secrets.CATNIP_HOSTNAME_B }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  #====================
  # Compile
  #====================

  # Demikernel 0
  build-demikernel0:
    name: Build Catnip
    needs: [setup-demikernel0]
    uses: demikernel/workflows/.github/workflows/compile.yml@dev
    with:
      target: "all PROFILER=yes LIBOS=catnip"
    secrets:
      host: ${{ secrets.CATNIP_HOSTNAME_A }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  # Demikernel 1
  build-demikernel1:
    name: Build Catnip
    needs: [setup-demikernel1]
    uses: demikernel/workflows/.github/workflows/compile.yml@dev
    with:
      target: "all PROFILER=yes LIBOS=catnip"
    secrets:
      host: ${{ secrets.CATNIP_HOSTNAME_B }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  #====================
  # Cleanup
  #====================

  # Demikernel 0
  cleanup-demikernel0:
    name: Cleanup
    needs: [build-demikernel0]
    uses: demikernel/workflows/.github/workflows/cleanup.yml@dev
    secrets:
      host: ${{ secrets.CATNIP_HOSTNAME_A }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  # Demikernel 1
  cleanup-demikernel1:
    name: Cleanup
    needs: [build-demikernel1]
    uses: demikernel/workflows/.github/workflows/cleanup.yml@dev
    secrets:
      host: ${{ secrets.CATNIP_HOSTNAME_B }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}
